version: '2'

services:
  flask-restx-boilerplate:
    image: pmint93/flask-restx-boilerplate:develop
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    tty: true
    stdin_open: true
